// label: FORM
export const FORM_QTY = 'qty';
export const FORM_PAYMENT = 'payment';
export const FORM_CONTACT = 'contact';

export const START_FETCH_FORM = 'START_FETCH_FORM';
export const SUCCESS_FETCH_FORM = 'SUCCESS_FETCH_FORM';
export const FAILURE_FETCH_FORM = 'FAILURE_FETCH_QTY_FORM';

export const START_FETCH_CARDS_LIST = 'START_FETCH_CARDS_LIST';
export const SUCCESS_FETCH_CARDS_LIST = 'SUCCESS_FETCH_CARDS_LIST';
export const FAILURE_FETCH_CARDS_LIST = 'FAILURE_FETCH_CARDS_LIST';

export const START_FETCH_TOTAL_MONTHS = 'START_FETCH_TOTAL_MONTHS';
export const SUCCESS_FETCH_TOTAL_MONTHS = 'SUCCESS_FETCH_TOTAL_MONTHS';
export const FAILURE_FETCH_TOTAL_MONTHS = 'FAILURE_FETCH_TOTAL_MONTHS';

export const SUCCESS_SET_QTY = 'SUCCESS_SET_QTY';

export const SUCCESS_SET_IS_MOBILE = 'SUCCESS_SET_IS_MOBILE';
